baseConfig: ./tsconfig.base.json
presets: 
  default: 
    compilerOptions: 
      rootDir: 'src'
      outDir: 'dist'
      incremental: true
      tsBuildInfoFile: 'dist/.tsbuildinfo'
    include:
      - src
    exclude: 
      - src/**.spec.ts
      - src/**.spec.tsx
  json: 
    include: 
      - 'src/**/*.json'
