plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.js

initScope: tscmono
initFields:
  main: dist/index.js
  version: "0.1.0"
  license: MIT
  publishConfig: 
    access: public
  author:
    email: sabinmarcu@gmail.com
    name: Sabin Marcu

changesetIgnorePatterns:
  - "**/LICENSE"
  - "**/README.md"
  - ".github/workflows/*"

npmAuthToken: ${YARN_NPM_AUTH_TOKEN:-NO_TOKEN}

packageExtensions:
  "gatsby-plugin-mdx@*":
    dependencies:
      "@emotion/react": "*"
  "@babel/plugin-proposal-nullish-coalescing-operator@*":
    dependencies:
      "@babel/helper-plugin-utils": "*"
      "@babel/plugin-syntax-nullish-coalescing-operator": "*"
