name: Build and Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup
      run: yarn install
    - name: Build
      run: yarn run build
    - name: Publish
      run: yarn run publish-packages
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Save Versioning
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: Automatic Versioning
        commit_options: '---no-verify --signoff'
