name: Publishing

on:
  push:
    branches: [ master ]

jobs:
  build: 
    name: "Build Packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup
      run: yarn install
    - name: Build
      run: yarn run build-packages
    - name: Save Built Files
      uses: actions/upload-artifact@v2
      with:
        name: built-repo
        path: packages
    

  publish:
    name: "Publish Packages"
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download Built Files
      uses: actions/download-artifact@v2
      with:
        name: built-repo
        path: packages
    - name: Setup
      run: yarn install
    - name: Check Versioning
      run: yarn publish:check
    - name: Apply Versioning
      run: yarn publish:apply
    - name: Publish
      run: yarn publish:run
      env:
        YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Save Versioning
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: Automatic Versioning
        commit_options: '--signoff'

  docs:
    name: "Build Docs"
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download Built Files
      uses: actions/download-artifact@v2
      with:
        name: built-repo
        path: packages
    - name: Setup
      run: yarn install
    - name: Build Docs
      run: yarn run docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
