name: Test

on: [push]

jobs: 
  build: 
    name: "Build Packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup
      run: yarn install
    - name: Build
      run: yarn run build-packages
    - name: Save Built Files
      uses: actions/upload-artifact@v2
      with:
        name: built-repo
        path: packages

  lint: 
    name: "Lint Packages"
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [14.x] 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download Built Files
      uses: actions/download-artifact@v2
      with:
        name: built-repo
        path: packages
    - name: Setup
      run: yarn install
    - name: Lint
      run: yarn lint

  test: 
    name: "Test Packages"
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        node-version: [14.x] 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download Built Files
      uses: actions/download-artifact@v2
      with:
        name: built-repo
        path: packages
    - name: Setup
      run: yarn install
    - name: Run Tests
      run: yarn test
    - name: Upload Coverage 
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/clover.xml
        fail_ci_if_error: true 
        verbose: true)
